/**
 * Brings the database up to the current schema and writes the first-run defaults (ADR-026).
 * Migrations are additive and versioned (`src/db/migrations/`, generated by `npm run db:generate`);
 * a failure throws and leaves the data untouched (the migration run is one transaction).
 */
import { migrate } from 'drizzle-orm/expo-sqlite/migrator';

import type { AppDb } from './database';
import { writeDefaults } from './defaults';
import { META_KEYS, getMeta, setMeta } from './metaRepository';
import migrations from './migrations/migrations';
import { meta } from './schema';

/** The schema version this build knows: the number of bundled migrations. */
export const SCHEMA_VERSION = migrations.journal.entries.length;

/** Whether the `meta` table exists yet (it doesn't before the first migration). */
function hasMetaTable(db: AppDb): boolean {
  try {
    db.select().from(meta).limit(1).all();
    return true;
  } catch {
    return false;
  }
}

/** Seeds the hero profile and the Home and Park equipment profiles once, on the first run. */
export function seedDefaults(db: AppDb, now: number): void {
  if (getMeta(db, META_KEYS.defaultsSeededAt) !== undefined) return;
  db.transaction((tx) => writeDefaults(tx, now));
}

/**
 * Runs pending migrations, records the schema version and seeds the defaults. Throws, without
 * changing anything, when the database was written by a newer app version (a downgrade).
 */
export async function migrateDatabase(db: AppDb, now: number): Promise<void> {
  if (hasMetaTable(db)) {
    const stored = Number(getMeta(db, META_KEYS.schemaVersion) ?? 0);
    if (stored > SCHEMA_VERSION) {
      throw new Error(
        `The database has schema version ${stored}, but this app only knows ${SCHEMA_VERSION}. ` +
          'Update the app; your data was not changed.',
      );
    }
  }
  await migrate(db, migrations);
  setMeta(db, META_KEYS.schemaVersion, String(SCHEMA_VERSION));
  seedDefaults(db, now);
}
