/**
 * Turns the YAML sources in `content/progressions/` into the checked dataset and its two generated
 * outputs: the typed module the app imports and the coach review sheet (ADR-016).
 *
 * Pure: it takes file contents and returns strings. File I/O lives in `scripts/progressions.ts`.
 */
import { nodeAttributes } from '@/domain/character';
import { BRANCHES } from '@/domain/types';
import type { Branch, ExerciseNode, Metric, Trial, ValidationIssue } from '@/domain/types';

import { parseBranchFile } from './progressionFormat';
import { BRANCH_NAMES } from './skills/branches';
import { validateNodes } from './validate';

/** Repo-relative, POSIX-style paths. */
export const PROGRESSIONS_DIR = 'content/progressions';
export const GENERATED_MODULE_PATH = 'src/data/skills/progressions.generated.ts';
export const REVIEW_SHEET_PATH = 'docs/review/progression-matrix.md';

export function branchFilePath(branch: Branch): string {
  return `${PROGRESSIONS_DIR}/${branch}.yaml`;
}

export interface SourceFile {
  /** Repo-relative POSIX path, e.g. `content/progressions/v_pull.yaml`. */
  path: string;
  text: string;
}

export interface BuildResult {
  /** Sorted by branch (in `BRANCHES` order), then chainOrder. */
  nodes: ExerciseNode[];
  issues: ValidationIssue[];
}

/** Parses every branch file, checks each against its file name, then validates the whole set. */
export function buildMatrix(files: readonly SourceFile[]): BuildResult {
  const issues: ValidationIssue[] = [];
  const nodes: ExerciseNode[] = [];
  const expected = new Set<string>(BRANCHES.map(branchFilePath));

  for (const file of files) {
    if (!expected.has(file.path)) {
      issues.push({
        file: file.path,
        message: `unexpected file; branch files are named after a branch (${BRANCHES.join(', ')})`,
      });
      continue;
    }
    const parsed = parseBranchFile(file.text, file.path);
    issues.push(...parsed.issues);
    if (parsed.branch !== undefined && branchFilePath(parsed.branch) !== file.path) {
      issues.push({
        file: file.path,
        message: `says 'branch: ${parsed.branch}' but the file name differs`,
      });
      continue;
    }
    nodes.push(...parsed.nodes);
  }
  for (const branch of BRANCHES) {
    if (!files.some((file) => file.path === branchFilePath(branch))) {
      issues.push({ file: branchFilePath(branch), message: 'file is missing' });
    }
  }

  const fileOf = (nodeId: string | undefined) => {
    const node = nodes.find((n) => n.id === nodeId);
    return node ? branchFilePath(node.branch) : undefined;
  };
  for (const issue of validateNodes(nodes)) issues.push({ ...issue, file: fileOf(issue.nodeId) });

  return { nodes: sortNodes(nodes), issues };
}

export function sortNodes(nodes: readonly ExerciseNode[]): ExerciseNode[] {
  const branchIndex = (branch: Branch) => BRANCHES.indexOf(branch);
  return [...nodes].sort(
    (a, b) => branchIndex(a.branch) - branchIndex(b.branch) || a.chainOrder - b.chainOrder,
  );
}

const GENERATED_HEADER = [
  '// GENERATED FILE - DO NOT EDIT.',
  '// Source: content/progressions/*.yaml. Rebuild with `npm run progressions:build`.',
].join('\n');

/** The typed module the app imports. The YAML is never parsed on the phone. */
export function renderGeneratedModule(nodes: readonly ExerciseNode[]): string {
  return [
    GENERATED_HEADER,
    "import type { ExerciseNode } from '@/domain/types';",
    '',
    `export const GENERATED_NODES: readonly ExerciseNode[] = ${JSON.stringify(nodes, null, 2)};`,
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------------------------
// Coach review sheet
// ---------------------------------------------------------------------------------------------

const UNIT: Record<Metric, string> = {
  reps: 'reps',
  hold_s: 's hold',
  eccentric_s: 's lowering',
  load_xbw: '× bodyweight',
};

function formatTrial(metric: Metric, trial: Trial): string {
  if (metric === 'eccentric_s') {
    return `${trial.sets} × ${trial.reps ?? 1} lowerings of ${trial.target} s`;
  }
  if (metric === 'load_xbw') {
    return `${trial.sets} × ${trial.reps ?? 1} reps at ${trial.target} × bodyweight`;
  }
  return `${trial.sets} × ${trial.target} ${UNIT[metric]}`;
}

function cell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

/** Markdown sheet for a coach: one table per branch plus an empty "Coach notes" column. */
export function renderReviewSheet(nodes: readonly ExerciseNode[]): string {
  const byId = new Map(nodes.map((node) => [node.id, node]));
  const reviewed = nodes.filter((node) => node.review.status === 'coach_reviewed').length;
  const flagged = nodes.filter((node) => node.verify !== undefined).length;

  const lines: string[] = [
    '# Progression matrix: coach review sheet',
    '',
    '> Generated by `npm run progressions:review` from `content/progressions/*.yaml`. Do not edit',
    '> this file; it is overwritten. Coaches: write comments in the "Coach notes" column of a copy or',
    "> printout (or in a PR comment). Contributors then copy them into the node's `review.notes` in",
    '> the YAML file and set `review.status: coach_reviewed` once it is signed off.',
    '',
    `**${nodes.length} nodes**, ${reviewed} coach-reviewed, ${flagged} flagged ⚠ (needs verifying).`,
    '',
    '- **Description** = the short text the app shows: what the exercise is and what it looks ' +
      'like (not the cues). Please check it matches the exercise.',
    '- **OG** = Overcoming Gravity 2 difficulty level (0 = foundation, below OG level 1; 17 = hardest).',
    '- **Prerequisites** = other exercises that must reach the given level (L1–L10; L5 = Proficient) ' +
      'first. *(rec.)* = recommended only, does not lock.',
    '- **Equipment**: "or" separates alternatives; "+" means both are needed.',
    '- **Trains** = the character attributes the exercise pays into. Derived from its movement ' +
      "patterns; an entry with * comes from the node's own `trains:` line (change it there).",
    '',
  ];

  for (const branch of BRANCHES) {
    const chain = nodes.filter((node) => node.branch === branch);
    lines.push(`## ${BRANCH_NAMES[branch]} (\`${branch}\`)`, '');
    if (chain.length === 0) {
      lines.push('_No nodes yet._', '');
      continue;
    }
    lines.push(
      '| # | Exercise | Description | OG | Metric | Working range | Trial | Prerequisites | Trains | Equipment | Sources | ⚠ Verify | Review | Coach notes |',
      '|---|---|---|---|---|---|---|---|---|---|---|---|---|---|',
    );
    for (const node of chain) {
      const flags = [node.legendary ? 'legendary' : '', node.straightArm ? 'straight-arm' : '']
        .filter(Boolean)
        .join(', ');
      const prerequisites = node.prerequisites
        .map((p) => {
          const name = byId.get(p.nodeId)?.name ?? p.nodeId;
          const kind = p.kind === 'recommended' ? ' *(rec.)*' : '';
          return `${name} L${p.minLevel}${kind}`;
        })
        .join('; ');
      const review = node.review.notes
        ? `${node.review.status}: ${node.review.notes}`
        : node.review.status;
      const row = [
        String(node.chainOrder),
        `**${node.name}** \`${node.id}\`${flags ? ` (${flags})` : ''}`,
        node.description,
        String(node.ogLevel),
        node.metric,
        `${node.workingRange.min}–${node.workingRange.max} ${UNIT[node.metric]}`,
        formatTrial(node.metric, node.trial),
        prerequisites || '—',
        nodeAttributes(node).join(', ') + (node.trains ? ' *' : ''),
        node.equipment.map((option) => option.join(' + ')).join(' or '),
        node.sourceUrls.map((url, i) => `[${i + 1}](${url})`).join(' '),
        node.verify ? `⚠ ${node.verify}` : '',
        review,
        '',
      ].map(cell);
      lines.push(`| ${row.join(' | ')} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}
